// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.get('playerHand').on('busted', (function(_this) {
        return function() {
          alert('you lose!!');
          return _this.set('playerHand', deck.dealPlayer());
        };
      })(this));
      this.get('playerHand').on('stand', (function(_this) {
        return function() {
          return _this.get('dealerHand').dealPlay(_this.get('playerHand').scores());
        };
      })(this));
      this.get('dealerHand').on('dealerBust', (function(_this) {
        return function() {
          return alert('you win!!');
        };
      })(this));
      this.get('dealerHand').on('dealerWin', (function(_this) {
        return function() {
          return alert('you loser you loser!!!');
        };
      })(this));
      this.get('dealerHand').on('tie', (function(_this) {
        return function() {
          return alert('we tied but house always wins, pay me!!');
        };
      })(this));
      return this.get('dealerHand').on('reveal', (function(_this) {
        return function() {
          return _this.set('revealed', true);
        };
      })(this));
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
