// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      return this.add(this.deck.pop()).last();
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (score > 21) {
        this.trigger('busted');
        return [score];
      } else {
        if (hasAce) {
          if (score + 11 > 21) {
            return [score];
          } else {
            return [score + 10];
          }
        } else {
          return [score];
        }
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('stand');
    };

    Hand.prototype.dealPlay = function(playerScore) {
      var dealerScore;
      if (!this.at(0).get('revealed')) {
        this.at(0).flip();
      }
      dealerScore = this.scores();
      console.log(dealerScore);
      console.log(playerScore);
      if (dealerScore[0] < 17 && dealerScore[0] < playerScore[0]) {
        this.hit();
        this.dealPlay(playerScore);
      }
      if (dealerScore[0] >= 17 && dealerScore[0] < playerScore[0]) {
        this.hit();
        this.dealPlay(playerScore);
      }
      if (dealerScore[0] >= 17 && dealerScore[0] < 21 && dealerScore[0] > playerScore[0]) {
        this.trigger('dealerWin');
      }
      if (dealerScore[0] > 21) {
        this.trigger('dealerBust');
      }
      if (dealerScore[0] === 21) {
        if (dealerScore[0] > playerScore[0]) {
          this.trigger('dealerWin');
        }
        if (dealerScore[0] === playerScore[0]) {
          this.trigger('tie');
        }
      }
      if (dealerScore[0] === playerScore[0]) {
        return this.trigger('tie');
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
